### ISSUE TITLE
Breaks in IE8

### ISSUE THREAD

**Issue by bmakuh** [reflux/reflux-core#11]
In the `extend` implementation in [utils.js](https://github.com/reflux/reflux-core/blob/master/src/utils.js#L27),  the function checks to see if `Object.defineProperty` exists and then uses it if it is. This is not IE8-compatible, though, because while IE8 includes an implementation of `defineProperty`, [it only works on DOM objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty). 

``` js
if (Object.getOwnPropertyDescriptor && Object.defineProperty) {
    var propertyDescriptor = Object.getOwnPropertyDescriptor(source, prop);
    Object.defineProperty(obj, prop, propertyDescriptor);
} else {
    obj[prop] = source[prop];
}
```

**Comment by bmakuh** [comment]
I know that the goal was to avoid importing lodash/underscore, but maybe importing _only_ `_.assign` would be an acceptable solution? https://github.com/lodash/lodash/blob/3.2.0-npm-packages/lodash.assign/index.js

**Comment by ce07c3** [comment]
Same in Safari.

**Comment by bmakuh** [comment]
@ce07c3 which version of Safari?

**Comment by ce07c3** [comment]
Safari 9. It should work, though, but I am getting an error specifically for the `defineProperty` call. However, not for every instance of the `obj` argument.

**Comment by spoike** [comment]
I'm planning to use Object.assign instead, that way you only need to use a ES6 shim that is IE8 compatible.

**Comment by ce07c3** [comment]
:+1:

**Comment by devinivy** [comment]
@spoike Using `Object.assign()` [this test](https://github.com/reflux/reflux-core/blob/c88131847c701bb773af4e96eadc5807df409f06/test/creatingStores.spec.js#L355-L367) would fail.  Rather than copying the getter descriptor, the getter is accessed and its value is copied.

**Comment by spoike** [comment]
@devinivy: Well, that's a weird test and must have missed it when I accepted the associated PR... Reflux stores (and actions) aren't supposed to have getters and setters, the data should be passed through the event instead.

Anyone have any issues with this functionality removed? I will probably have to bump up the minor version number for this if there is.

**Comment by devinivy** [comment]
Ah, I haven't seen the associated PR for this.  Maybe this issue was worked-around in some way?  If reflux is not trying to support IE8, I don't see any reason to change how extend works.

**Comment by BryanGrezeszak** [comment]
Not a bug, just a really old browser.
