### ISSUE TITLE
Error is thrown depending on order when listeners are registered

### ISSUE THREAD

**Issue by spoike** [reflux/reflux-core#12]
Need to verify if reflux/refluxjs#38 is working or not.

> The following error is produced in certain configurations on [this line](https://github.com/spoike/refluxjs/blob/master/src/all.js#L31):
> 
>    Uncaught TypeError: Cannot read property 'hasListener' of undefined
> 
> This happens when you register composed listeners before other stores and actions. The `args` array has a length set, but is an array of undefined.
> 
> Testcase pseudo code:
> 
> ``` javascript
> // Inside a store init
> var join = Reflux.all(testAction1, testAction2);
> 
> this.listenTo(join, resetCallback);
> this.listenTo(testAction2, commonlyCalledCallback); // throws the error from here
> ```
> 
> Workaround is to listen to the joined actions/stores afterwards:
> 
> ``` javascript
> this.listenTo(testAction2, commonlyCalledCallback);
> this.listenTo(join, resetCallback);
> // no errors thrown, works as expected
> ```

**Comment by devinivy** [comment]
This appears to be fixed: https://github.com/reflux/reflux-core/blob/3e7c9d816a504a1f6dd12337840ad589f5bfc874/test/composedListenable.spec.js#L182-L202

In case there's still any doubt around its usage with `createStore()`, this also passes: https://github.com/devinivy/reflux-core/commit/cce2e4d8352bd65ddd7ac37c4313691f7e31d4e1

**Comment by spoike** [comment]
Thanks @devinivy. Is it okay for me to pull in your commit?

**Comment by devinivy** [comment]
Go for it!  Made a PR https://github.com/reflux/reflux-core/pull/18

**Comment by devinivy** [comment]
That test was pulled-in to master.  Seems this is fixed :+1:
