### ISSUE TITLE
A Guide for creating reflux-xxx

### ISSUE THREAD

**Issue by morlay** [reflux/reflux-core#2]
Really thanks the `reflux-core` starting.

Recently, I have to use the [riot](https://github.com/riot/riot), and still missing the reflux, so extends it to [reflux-riot](https://github.com/morlay/reflux-riot) it works well, and still in process.

Then need a suggest to complete it.  
For now i just wrap the `reflux-core` then add the mixins apis, then we can use reflux as old ways. 
or should we make this like react 0.14 did (react-core && react-dom), one for core, another for mixins ?

**Comment by spoike** [comment]
Great idea. There is a little discussion about a `Reflux#use` method here for plug-ins: https://github.com/reflux/refluxjs/issues/380

When I've integrated `reflux-core@0.2.0-rc` in `reflux` (for react bits), and add the `Reflux#use` method I'll try to write a concise guide about it on the README.

**Comment by spoike** [comment]
Guide is up on the README.

**Comment by spoike** [comment]
Let me know if there are any problems with the 0.2.0 package or if info is missing in the README.
