### ISSUE TITLE
CreateAction breaks in IE8

### ISSUE THREAD

**Issue by npoy** [reflux/reflux-core#33]
Hi, i'm trying to support ie8 and after use polyfills and fix all the problems, i did find that reflux-core is throwing this error:

![image](https://cloud.githubusercontent.com/assets/14371735/23261214/0e6361d2-f9b4-11e6-9368-cbf67b8a9e27.png)

I can see that reflux-core use getters and setters but isn't compatible with ie8. I readed all the ie8 issues but not any could help me.

Thanks.

**Comment by BryanGrezeszak** [comment]
Sorry, but Reflux does not support IE8.
