### ISSUE TITLE
extra function name 

### ISSUE THREAD

**Issue by will-** [reflux/reflux-core#4]
https://github.com/reflux/reflux-core/blob/master/src/createAction.js#L55

Tried to build reflux and found this line different in npm version.

``` javascript
var functor = function functor() {
        var triggerType = functor.sync ? "trigger" : _.environment.hasPromise ? "triggerPromise" : "triggerAsync";
        return functor[triggerType].apply(functor, arguments);
    };
```

Calling actions may  fail in  ie8 after `grunt-contrib-uglify` because of the extra function name `functor`.
Am I missing something?

**Comment by devinivy** [comment]
I now realize that this issue came first, but checkout https://github.com/reflux/reflux-core/issues/16.

**Comment by spoike** [comment]
Closing this as duplicate and there is more information in #16.
