### ISSUE TITLE
Examples/documentation of using reflux-core?

### ISSUE THREAD

**Issue by kad3nce** [reflux/reflux-core#5]
After reading [this article](http://www.thesoftwaresimpleton.com/blog/2015/03/13/ember-reflux/) on using a Reflux style architecture in an Ember app, I'm interested in experimenting with reflux-core in my Ember app. The blog post author rolls his own "poor-man's Reflux", but I think it makes sense to use reflux-core as it's battle-tested. I'm just wondering if there's any documentation or examples on using reflux-core in something other than a React app?

Thanks for any help.

**Comment by spoike** [comment]
I currently only 3rd party example I know of is riot: https://www.npmjs.com/package/reflux-riot

I think it will be interesting to see if people will use reflux-core in other view-engine libraries. The react bits are removed in the core. If you want to see the extensions made for react, check out the refluxjs's source code.

**Comment by spoike** [comment]
I will make a note of reflux-core usage down the line as we'll have the docs site up with content.

**Comment by brigand** [comment]
I'm using reflux-core with react. I just have a small decorator that allows me to listen to stores (es6 classes so no mixins). I originally did it because I'm using the react 0.14-rc and reflux has a peer dependency with an upper bound, but I prefer it like this. You could publish the mixins/decorators as separate packages and have reflux on npm become reflux-core.

``` js
import React, {PropTypes} from 'react';

export default function providesStore(store, Component){
  if (arguments.length < 2) return providesStore.bind(null, store);

  let propName = store.name || 'store';
  var propTypes = Component.propTypes || {};
  var matchedPropName = Object.keys(propTypes).find((key) => {
    return propTypes[key] && propTypes[key]._refluxStore === store;
  });
  if (matchedPropName) {
    propName = matchedPropName;
  }

  return class StoreProvider extends React.Component {
    constructor(){
      super();
      this.state = {
        storeState: store.getState ? store.getState() : undefined,
      };
    }
    componentDidMount(){
      this.unsubscribe = store.listen((storeState) => {
        this.setState({storeState});
      });
    }
    componentWillUnmount(){
      this.unsubscribe();
    }
    render(){
      return (
        <Component
          {...this.props}
          {...{[propName]: this.state.storeState}}
        />
      );
    }
  };
}

providesStore.getPropType = (store) => {
  var type = (...args) => PropTypes.any(...args);
  type._refluxStore = store;
  return type;
}
```

Example usage:

``` js
import React, {PropTypes} from 'react';
import {Users} from '../utils/actions';
import providesStore from '../utils/decorators/providesStore';
import UserStore from '../stores/UserStore';
import UserDetails from '../molecules/UserDetails';

export default
@providesStore(UserStore)
class UserDetailsWrapper extends React.Component {
  static propTypes = {
    users: providesStore.getPropType(UserStore),
    userId: PropTypes.string.isRequired,
  };

  componentWillReceiveProps(nextProps){
    if (!this.props.users[nextProps.userId]) {
      Users.get(nextProps.userId);
    }
  }

  componentDidMount(){
    if (!this.props.users[this.props.userId]) {
      Users.get(this.props.userId);
    }
  }

  render(){
    var user = this.props.users[this.props.userId];
    if (!user) {
      return null;
    }

    return (
      <UserDetails user={user} />
    );
  }
}
```

**Comment by spoike** [comment]
@brigand I agree with you that the different mixins should be their own npm package. `providesStore` should really be published as an npm package btw. :-) :+1:

**Comment by brigand** [comment]
Thanks, published as reflux-provides-store.

**Comment by mcoetzee** [comment]
Nice one @brigand - thanks for sharing

**Comment by yonatanmn** [comment]
@brigand , take a look
 https://github.com/yonatanmn/reflux-state-mixin/blob/master/connectDecorator.js

similar, but controls state rather than props (like reflux.connect)

**Comment by brigand** [comment]
Cool :-)

**Comment by devinivy** [comment]
For those interested using reflux with polymer, https://github.com/devinivy/funk!

**Comment by devinivy** [comment]
Definitely feel free to continue conversation about this over at https://github.com/reflux/discuss !
